#!/usr/bin/python3

def even_odd(number):
    if number % 2 == 0:
        return "Even"
    else:
        return "Odd"


user_input = input("Enter an integer: ")

try:
    number = int(user_input)
    result = even_odd(number)
    print(f"The number {number} is {result}.")
except ValueError:
    print("Invalid input. Please enter a valid integer.")
